/**
 * Memory Init Core (WU-1464)
 *
 * Core logic for initializing memory layer in a repository.
 * Creates .beacon/memory/ directory with empty memory.jsonl and config.yaml.
 *
 * @see {@link tools/__tests__/mem-init.test.mjs} - Tests
 * @see {@link tools/lib/memory-store.mjs} - Memory store operations
 * @see {@link tools/lib/memory-schema.mjs} - Memory schema definitions
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import yaml from 'yaml';

/**
 * Memory layer file/directory paths
 */
export const MEMORY_PATHS = {
  /** Memory directory relative to project root */
  MEMORY_DIR: '.beacon/memory',

  /** Memory JSONL file name */
  MEMORY_FILE: 'memory.jsonl',

  /** Config YAML file name */
  CONFIG_FILE: 'config.yaml',
};

/**
 * Default memory layer configuration
 *
 * Retention values are in seconds:
 * - ephemeral: 0 (immediate discard)
 * - session: 3600 (1 hour)
 * - wu: 604800 (7 days)
 * - project: -1 (never expire)
 */
export const DEFAULT_CONFIG = {
  /** Config schema version */
  version: 1,

  /** Retention policy for each lifecycle */
  retention: {
    /** Ephemeral nodes are discarded immediately after use */
    ephemeral: 0,
    /** Session nodes expire after 1 hour */
    session: 3600,
    /** WU nodes expire after 7 days */
    wu: 604800,
    /** Project nodes never expire (-1 = infinite) */
    project: -1,
  },
};

/**
 * Check if a file exists
 *
 * @param filePath - Path to check
 * @returns True if file exists
 */
async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Generate config.yaml content from DEFAULT_CONFIG
 *
 * @returns YAML content string
 */
function generateConfigYaml(): string {
  const header = '# Memory layer configuration\n# Generated by pnpm mem:init (WU-1464)\n';
  return header + yaml.stringify(DEFAULT_CONFIG);
}

/**
 * Memory initialization paths
 */
interface InitMemoryPaths {
  memoryDir: string;
  memoryJsonl: string;
  configYaml: string;
}

/**
 * Memory initialization created flags
 */
interface InitMemoryCreated {
  directory: boolean;
  memoryJsonl: boolean;
  configYaml: boolean;
}

/**
 * Memory initialization result
 */
export interface InitMemoryResult {
  success: boolean;
  alreadyInitialized: boolean;
  paths: InitMemoryPaths;
  created: InitMemoryCreated;
}

/**
 * Initialize memory layer in a repository.
 *
 * Creates:
 * - .beacon/memory/ directory
 * - memory.jsonl (empty if not exists)
 * - config.yaml (default settings if not exists)
 *
 * Idempotent: Running multiple times does not corrupt existing data.
 *
 * @param baseDir - Base directory of the repository
 * @returns Result object with success, paths, and created flags
 *
 * @example
 * const result = await initMemory(process.cwd());
 * if (result.success) {
 *   console.log('Memory initialized at:', result.paths.memoryDir);
 * }
 */
export async function initMemory(baseDir: string): Promise<InitMemoryResult> {
  const memoryDir = path.join(baseDir, MEMORY_PATHS.MEMORY_DIR);
  const memoryJsonlPath = path.join(memoryDir, MEMORY_PATHS.MEMORY_FILE);
  const configYamlPath = path.join(memoryDir, MEMORY_PATHS.CONFIG_FILE);

  const result: InitMemoryResult = {
    success: false,
    alreadyInitialized: false,
    paths: {
      memoryDir,
      memoryJsonl: memoryJsonlPath,
      configYaml: configYamlPath,
    },
    created: {
      directory: false,
      memoryJsonl: false,
      configYaml: false,
    },
  };

  // Check if already initialized
  const dirExists = await fileExists(memoryDir);
  const memoryExists = await fileExists(memoryJsonlPath);
  const configExists = await fileExists(configYamlPath);

  if (dirExists && memoryExists && configExists) {
    result.alreadyInitialized = true;
  }

  // Create directory if needed
  if (!dirExists) {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- CLI tool creates .beacon/memory/ directory
    await fs.mkdir(memoryDir, { recursive: true });
    result.created.directory = true;
  }

  // Create empty memory.jsonl if needed
  if (!memoryExists) {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- CLI tool creates memory.jsonl
    await fs.writeFile(memoryJsonlPath, '', { encoding: 'utf-8' as BufferEncoding });
    result.created.memoryJsonl = true;
  }

  // Create config.yaml with defaults if needed
  if (!configExists) {
    const configContent = generateConfigYaml();
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- CLI tool creates config.yaml
    await fs.writeFile(configYamlPath, configContent, { encoding: 'utf-8' as BufferEncoding });
    result.created.configYaml = true;
  }

  result.success = true;
  return result;
}
