/**
 * @file wu-done-docs-generate.ts
 * @description Documentation regeneration utilities for wu:done
 *
 * WU-1061: Integrate docs:generate into wu:done for @lumenflow/* changes
 *
 * Detects changes to files that affect generated documentation and triggers
 * regeneration during wu:done (after gates pass, before metadata commit).
 */

import { execSync } from 'node:child_process';
import { getGitForCwd } from './git-adapter.js';
import { STDIO, PKG_MANAGER, SCRIPTS, PRETTIER_FLAGS } from './wu-constants.js';

/**
 * Pathspecs for files that affect generated documentation.
 * When any of these files change, docs:generate should be run.
 *
 * Based on .husky/hooks/docs-sync.ts patterns, expanded to match
 * all files that can affect CLI/config documentation.
 */
export const DOC_SOURCE_PATHSPECS = [
  'tools/generate-cli-docs.ts',
  'packages/@lumenflow/core/src/arg-parser.ts',
  'packages/@lumenflow/core/src/lumenflow-config-schema.ts',
  'packages/@lumenflow/core/src/index.ts',
  'packages/@lumenflow/cli/package.json',
  'packages/@lumenflow/cli/src/',
] as const;

/**
 * Output files generated by docs:generate.
 * These files are staged before the metadata commit.
 */
export const DOC_OUTPUT_FILES = [
  'apps/docs/src/content/docs/reference/cli.mdx',
  'apps/docs/src/content/docs/reference/config.mdx',
] as const;

/**
 * Check if any doc-source files changed compared to the base branch.
 * Uses git diff with pathspecs for efficient detection.
 *
 * @param baseBranch - Base branch for comparison (e.g., 'main', 'origin/main')
 * @returns Promise<boolean> - True if doc-source files changed
 */
export async function hasDocSourceChanges(baseBranch: string): Promise<boolean> {
  try {
    const gitAdapter = getGitForCwd();
    const diff = await gitAdapter.raw([
      'diff',
      `${baseBranch}...HEAD`,
      '--name-only',
      '--',
      ...DOC_SOURCE_PATHSPECS,
    ]);
    return diff.trim().length > 0;
  } catch {
    // Fail-safe: don't regenerate on git errors
    return false;
  }
}

/**
 * Stage doc output files for the metadata commit.
 *
 * @returns Promise<void>
 */
export async function stageDocOutputs(): Promise<void> {
  const gitAdapter = getGitForCwd();
  await gitAdapter.add([...DOC_OUTPUT_FILES]);
}

/**
 * Run turbo docs:generate to regenerate documentation.
 * Turbo handles build dependencies and caching.
 *
 * @param repoRoot - Repository root directory
 * @returns void
 */
export function runDocsGenerate(repoRoot: string): void {
  // eslint-disable-next-line sonarjs/no-os-command-from-path -- pnpm resolved from PATH; workflow tooling orchestration
  execSync('pnpm turbo docs:generate', {
    cwd: repoRoot,
    stdio: STDIO.INHERIT,
    encoding: 'utf-8',
  });
}

/**
 * Format generated doc output files with prettier.
 *
 * @param repoRoot - Repository root directory for running prettier
 * @returns void
 */
export function formatDocOutputs(repoRoot: string): void {
  const files = DOC_OUTPUT_FILES.map((file) => `"${file}"`).join(' ');
  const prettierCmd = `${PKG_MANAGER} ${SCRIPTS.PRETTIER} ${PRETTIER_FLAGS.WRITE} ${files}`;
  execSync(prettierCmd, {
    cwd: repoRoot,
    stdio: STDIO.INHERIT,
    encoding: 'utf-8',
  });
}

/**
 * Result of the docs regeneration check.
 */
export interface DocsRegenerationResult {
  /** Whether doc-source files changed */
  docsChanged: boolean;
  /** Whether docs were regenerated */
  regenerated: boolean;
}

/**
 * Options for maybeRegenerateAndStageDocs.
 */
export interface MaybeRegenerateDocsOptions {
  /** Base branch for comparison (e.g., 'main', calculated from defaultBranchFrom) */
  baseBranch: string;
  /** Repository root directory for running turbo */
  repoRoot: string;
}

/**
 * Detect doc-source changes and regenerate docs if needed.
 * This is the main integration point for wu:done.
 *
 * Call this BEFORE stageAndFormatMetadata() to include doc outputs
 * in the single atomic commit.
 *
 * @param options - Detection and regeneration options
 * @returns Promise<DocsRegenerationResult> - Whether docs changed and were regenerated
 */
export async function maybeRegenerateAndStageDocs(
  options: MaybeRegenerateDocsOptions,
): Promise<DocsRegenerationResult> {
  const { baseBranch, repoRoot } = options;

  // Check if doc-source files changed
  const docsChanged = await hasDocSourceChanges(baseBranch);

  if (!docsChanged) {
    console.log('[wu:done] No doc-source changes detected, skipping docs:generate');
    return { docsChanged: false, regenerated: false };
  }

  console.log('[wu:done] Doc-source changes detected, running turbo docs:generate...');

  // Run turbo docs:generate (Turbo handles caching and dependencies)
  runDocsGenerate(repoRoot);

  // Format the generated doc outputs before staging
  formatDocOutputs(repoRoot);

  // Stage the doc output files
  await stageDocOutputs();

  console.log('[wu:done] Documentation regenerated and staged');

  return { docsChanged: true, regenerated: true };
}
