/**
 * @file init.ts
 * LumenFlow project scaffolding command (WU-1045)
 * WU-1006: Library-First - use core defaults for config generation
 * WU-1028: Vendor-agnostic core + vendor overlays
 * WU-1085: Added createWUParser for proper --help support
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as yaml from 'yaml';
import { getDefaultConfig, createWUParser, WU_OPTIONS } from '@lumenflow/core';
// WU-1067: Import GATE_PRESETS for --preset support
import { GATE_PRESETS } from '@lumenflow/core/dist/gates-config.js';

/**
 * WU-1085: CLI option definitions for init command
 */
const INIT_OPTIONS = {
  full: {
    name: 'full',
    flags: '--full',
    description: 'Add docs + agent onboarding + task scaffolding',
  },
  framework: {
    name: 'framework',
    flags: '--framework <name>',
    description: 'Add framework hint + overlay docs',
  },
  vendor: {
    name: 'vendor',
    flags: '--vendor <type>',
    description: 'Vendor type (claude, cursor, aider, all, none)',
  },
  preset: {
    name: 'preset',
    flags: '--preset <preset>',
    description: 'Gate preset for config (node, python, go, rust, dotnet)',
  },
  force: WU_OPTIONS.force,
};

/**
 * WU-1085: Parse init command options using createWUParser
 * Provides proper --help, --version, and option parsing
 */
export function parseInitOptions(): {
  force: boolean;
  full: boolean;
  framework?: string;
  vendor?: VendorType;
  preset?: GatePresetType;
} {
  const opts = createWUParser({
    name: 'lumenflow-init',
    description: 'Initialize LumenFlow in a project',
    options: Object.values(INIT_OPTIONS),
  });

  return {
    force: opts.force ?? false,
    full: opts.full ?? false,
    framework: opts.framework,
    vendor: opts.vendor as VendorType | undefined,
    preset: opts.preset as GatePresetType | undefined,
  };
}

/**
 * Supported vendor integrations
 */
export type VendorType = 'claude' | 'cursor' | 'aider' | 'all' | 'none';

export type DefaultClient = 'claude-code' | 'none';

// WU-1067: Supported gate presets for config-driven gates
export type GatePresetType = 'node' | 'python' | 'go' | 'rust' | 'dotnet';

export interface ScaffoldOptions {
  force: boolean;
  full: boolean;
  framework?: string;
  vendor?: VendorType;
  defaultClient?: DefaultClient;
  /** WU-1067: Gate preset to populate in gates.execution */
  gatePreset?: GatePresetType;
}

export interface ScaffoldResult {
  created: string[];
  skipped: string[];
}

const CONFIG_FILE_NAME = '.lumenflow.config.yaml';
const FRAMEWORK_HINT_FILE = '.lumenflow.framework.yaml';
const LUMENFLOW_DIR = '.lumenflow';
const LUMENFLOW_AGENTS_DIR = `${LUMENFLOW_DIR}/agents`;
const CLAUDE_DIR = '.claude';
const CLAUDE_AGENTS_DIR = path.join(CLAUDE_DIR, 'agents');

/**
 * Generate YAML configuration with header comment
 * WU-1067: Supports --preset option for config-driven gates
 */
function generateLumenflowConfigYaml(gatePreset?: GatePresetType): string {
  const header = `# LumenFlow Configuration\n# Generated by: lumenflow init\n# Customize paths based on your project structure\n\n`;
  const config = getDefaultConfig();
  config.directories.agentsDir = LUMENFLOW_AGENTS_DIR;

  // WU-1067: Add gates.execution section with preset if specified
  if (gatePreset && GATE_PRESETS[gatePreset]) {
    const presetConfig = GATE_PRESETS[gatePreset];
    (config.gates as Record<string, unknown>).execution = {
      preset: gatePreset,
      ...presetConfig,
    };
  }

  return header + yaml.stringify(config);
}

/**
 * Get current date in YYYY-MM-DD format
 */
function getCurrentDate(): string {
  return new Date().toISOString().split('T')[0];
}

/**
 * Normalize a framework name into display + slug
 */
function normalizeFrameworkName(framework: string): { name: string; slug: string } {
  const name = framework.trim();
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9-_]+/g, '-')
    .replace(/^-+|-+$/g, '');

  if (!slug) {
    throw new Error(`Invalid framework name: "${framework}"`);
  }

  return { name, slug };
}

/**
 * Process template content by replacing placeholders
 */
function processTemplate(content: string, tokens: Record<string, string>): string {
  let output = content;
  for (const [key, value] of Object.entries(tokens)) {
    output = output.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), value);
  }
  return output;
}

function getRelativePath(targetDir: string, filePath: string): string {
  return path.relative(targetDir, filePath).split(path.sep).join('/');
}

// Template for LUMENFLOW.md (main entry point)
const LUMENFLOW_MD_TEMPLATE = `# LumenFlow Workflow Guide\n\n**Last updated:** {{DATE}}\n\nLumenFlow is a vendor-agnostic workflow framework for AI-native software development.\n\n---\n\n## Critical Rule: ALWAYS Run wu:done\n\n**After completing work on a WU, you MUST run \`pnpm wu:done --id WU-XXXX\` from the main checkout.**\n\nThis is the single most forgotten step. Do NOT:\n- Write "To Complete: pnpm wu:done" and stop\n- Ask if you should run wu:done\n- Forget to run wu:done\n\n**DO**: Run \`pnpm wu:done --id WU-XXXX\` immediately after gates pass.\n\n---\n\n## Quick Start\n\n\`\`\`bash\n# 1. Create a WU\npnpm wu:create --id WU-XXXX --lane <Lane> --title "Title"\n\n# 2. Edit WU spec with acceptance criteria, then claim:\npnpm wu:claim --id WU-XXXX --lane <Lane>\ncd worktrees/<lane>-wu-xxxx\n\n# 3. Implement in worktree\n\n# 4. Run gates\npnpm gates --docs-only  # for docs changes\npnpm gates              # for code changes\n\n# 5. Complete (from main checkout)\ncd {{PROJECT_ROOT}}\npnpm wu:done --id WU-XXXX\n\`\`\`\n\n---\n\n## Core Principles\n\n1. **TDD**: Failing test -> implementation -> passing test (>=90% coverage on new code)\n2. **Library-First**: Search existing libraries before custom code\n3. **DRY/SOLID/KISS/YAGNI**: No magic numbers, no hardcoded strings\n4. **Worktree Discipline**: After \`wu:claim\`, work ONLY in the worktree\n5. **Gates Before Done**: All gates must pass before \`wu:done\`\n6. **Do Not Bypass Hooks**: No \`--no-verify\`, fix issues properly\n7. **Always wu:done**: Complete every WU by running \`pnpm wu:done\`\n\n---\n\n## Documentation Structure\n\n### Core (Vendor-Agnostic)\n\n- **LUMENFLOW.md** - This file, main entry point\n- **.lumenflow/constraints.md** - Non-negotiable workflow constraints\n- **.lumenflow/agents/** - Agent instructions (vendor-agnostic)\n- **.lumenflow.config.yaml** - Workflow configuration\n\n### Optional Overlays\n\n- **CLAUDE.md + .claude/agents/** - Claude Code overlay (auto if Claude Code detected)\n- **docs/04-operations/tasks/** - Task boards and WU storage (\`lumenflow init --full\`)\n- **docs/04-operations/_frameworks/<framework>/** - Framework overlay docs (\`lumenflow init --framework <name>\`)\n- **.lumenflow.framework.yaml** - Framework hint file (created with \`--framework\`)\n\n---\n\n## Worktree Discipline (IMMUTABLE LAW)\n\nAfter claiming a WU, you MUST work in its worktree:\n\n\`\`\`bash\n# 1. Claim creates worktree\npnpm wu:claim --id WU-XXX --lane <lane>\n\n# 2. IMMEDIATELY cd to worktree\ncd worktrees/<lane>-wu-xxx\n\n# 3. ALL work happens here\n\n# 4. Return to main ONLY to complete\ncd {{PROJECT_ROOT}}\npnpm wu:done --id WU-XXX\n\`\`\`\n\n---\n\n## Definition of Done\n\n- Acceptance criteria satisfied\n- Gates green (\`pnpm gates\` or \`pnpm gates --docs-only\`)\n- WU YAML status = \`done\`\n- \`wu:done\` has been run\n\n---\n\n## Commands Reference\n\n| Command           | Description                         |\n| ----------------- | ----------------------------------- |\n| \`pnpm wu:create\` | Create new WU spec                  |\n| \`pnpm wu:claim\`  | Claim WU and create worktree        |\n| \`pnpm wu:done\`   | Complete WU (merge, stamp, cleanup) |\n| \`pnpm gates\`     | Run quality gates                   |\n\n---\n\n## Constraints\n\nSee [.lumenflow/constraints.md](.lumenflow/constraints.md) for the 6 non-negotiable rules.\n\n---\n\n## Agent Onboarding\n\n- Start with **CLAUDE.md** if present (Claude Code overlay).\n- Add vendor-agnostic guidance in **.lumenflow/agents/**.\n- Add framework-specific notes in **docs/04-operations/_frameworks/<framework>/**.\n`;

// Template for .lumenflow/constraints.md
const CONSTRAINTS_MD_TEMPLATE = `# LumenFlow Constraints Capsule\n\n**Version:** 1.0\n**Last updated:** {{DATE}}\n\n## The 6 Non-Negotiable Constraints\n\n### 1. Worktree Discipline and Git Safety\nWork only in worktrees, treat main as read-only, never run destructive git commands on main.\n\n### 2. WUs Are Specs, Not Code\nRespect code_paths boundaries, no feature creep, no code blocks in WU YAML files.\n\n### 3. Docs-Only vs Code WUs\nDocumentation WUs use \`--docs-only\` gates, code WUs run full gates.\n\n### 4. LLM-First, Zero-Fallback Inference\nUse LLMs for semantic tasks, fall back to safe defaults (never regex/keywords).\n\n### 5. Gates and Skip-Gates\nComplete via \`pnpm wu:done\`; skip-gates only for pre-existing failures with \`--reason\` and \`--fix-wu\`.\n\n### 6. Safety and Governance\nRespect privacy rules, approved sources, security policies; when uncertain, choose safer path.\n\n---\n\n## Mini Audit Checklist\n\nBefore running \`wu:done\`, verify:\n\n- [ ] Working in worktree (not main)\n- [ ] Only modified files in \`code_paths\`\n- [ ] Gates pass\n- [ ] No forbidden git commands used\n- [ ] Acceptance criteria satisfied\n\n---\n\n## Escalation Triggers\n\nStop and ask a human when:\n- Same error repeats 3 times\n- Auth or permissions changes required\n- PII/PHI/safety issues discovered\n- Cloud spend or secrets involved\n`;

// Template for root CLAUDE.md
const CLAUDE_MD_TEMPLATE = `# Claude Code Instructions\n\n**Last updated:** {{DATE}}\n\nThis project uses LumenFlow workflow. For workflow documentation, see [LUMENFLOW.md](LUMENFLOW.md).\n\n---\n\n## Quick Start\n\n\`\`\`bash\n# 1. Claim a WU\npnpm wu:claim --id WU-XXXX --lane <Lane>\ncd worktrees/<lane>-wu-xxxx\n\n# 2. Work in worktree, run gates\npnpm gates\n\n# 3. Complete (ALWAYS run this!)\ncd {{PROJECT_ROOT}}\npnpm wu:done --id WU-XXXX\n\`\`\`\n\n---\n\n## Critical: Always wu:done\n\nAfter completing work, ALWAYS run \`pnpm wu:done --id WU-XXXX\`.\n\nSee [LUMENFLOW.md](LUMENFLOW.md) for full workflow documentation.\n`;

// Template for .claude/settings.json
const CLAUDE_SETTINGS_TEMPLATE = `{
  "$schema": "https://json.schemastore.org/claude-code-settings.json",
  "permissions": {
    "allow": [
      "Bash",
      "Read",
      "Write",
      "Edit",
      "WebFetch",
      "WebSearch"
    ],
    "deny": [
      "Read(./.env)",
      "Read(./.env.*)",
      "Write(./.env*)",
      "Bash(git reset --hard *)",
      "Bash(git stash *)",
      "Bash(git clean -fd *)",
      "Bash(git push --force *)",
      "Bash(git push -f *)",
      "Bash(git commit --no-verify *)",
      "Bash(HUSKY=0 *)",
      "Bash(rm -rf /*)",
      "Bash(sudo *)",
      "Bash(git worktree remove *)",
      "Bash(git worktree prune *)"
    ]
  }
}
`;

// Template for .cursor/rules.md
const CURSOR_RULES_TEMPLATE = `# Cursor Rules\n\nThis project uses LumenFlow workflow. See [LUMENFLOW.md](../LUMENFLOW.md).\n\n## Critical Rules\n\n1. **Always run wu:done** - After gates pass, run \`pnpm wu:done --id WU-XXX\`\n2. **Work in worktrees** - After \`wu:claim\`, work only in the worktree\n3. **Never bypass hooks** - No \`--no-verify\`\n4. **TDD** - Write tests first\n\n## Forbidden Commands\n\n- \`git reset --hard\`\n- \`git push --force\`\n- \`git stash\` (on main)\n- \`--no-verify\`\n`;

// Template for .aider.conf.yml
const AIDER_CONF_TEMPLATE = `# Aider Configuration for LumenFlow Projects\n# See LUMENFLOW.md for workflow documentation\n\nmodel: gpt-4-turbo\nauto-commits: false\ndirty-commits: false\n\nread:\n  - LUMENFLOW.md\n  - .lumenflow/constraints.md\n`;

// Template for docs/04-operations/tasks/backlog.md
const BACKLOG_TEMPLATE = `---\nsections:\n  ready:\n    heading: '## 🚀 Ready (pull from here)'\n    insertion: after_heading_blank_line\n  in_progress:\n    heading: '## 🔧 In progress'\n    insertion: after_heading_blank_line\n  blocked:\n    heading: '## ⛔ Blocked'\n    insertion: after_heading_blank_line\n  done:\n    heading: '## ✅ Done'\n    insertion: after_heading_blank_line\n---\n\n# Backlog (single source of truth)\n\n## 🚀 Ready (pull from here)\n\n(No items ready)\n\n## 🔧 In progress\n\n(No items in progress)\n\n## ⛔ Blocked\n\n(No items blocked)\n\n## ✅ Done\n\n(No items completed yet)\n`;

// Template for docs/04-operations/tasks/status.md
const STATUS_TEMPLATE = `# Status (active work)\n\n## In Progress\n\n(No items in progress)\n\n## Blocked\n\n(No items blocked)\n\n## Completed\n\n(No items completed yet)\n`;

// Template for docs/04-operations/tasks/templates/wu-template.yaml
const WU_TEMPLATE_YAML = `# Work Unit Template (LumenFlow WU Schema)\n#\n# Copy this template when creating new WUs. Fill in all required fields and\n# remove optional fields if not needed.\n#\n# If you used "lumenflow init --full", this template lives at:\n# docs/04-operations/tasks/templates/wu-template.yaml\n\n# Required: Unique work unit identifier (format: WU-NNN)\nid: WU-XXX\n\n# Required: Short, descriptive title (max 80 chars)\ntitle: 'Your WU title here'\n\n# Required: Lane (Parent: Sublane format)\nlane: 'Framework: CLI'\n\n# Required: Type of work\ntype: 'feature' # feature | bug | documentation | process | tooling | chore | refactor\n\n# Required: Current status\nstatus: 'ready' # ready | in_progress | blocked | done | cancelled\n\n# Required: Priority\npriority: P2 # P0 | P1 | P2 | P3\n\n# Required: Creation date (YYYY-MM-DD)\ncreated: {{DATE}}\n\n# Required: Owner/assignee (email)\nassigned_to: 'unassigned@example.com'\n\n# Required: Description\ndescription: |\n  Context: ...\n  Problem: ...\n  Solution: ...\n\n# Required: Acceptance criteria (testable, binary)\nacceptance:\n  - Criterion 1 (specific, measurable, testable)\n  - Criterion 2 (binary pass/fail)\n  - Documentation updated\n\n# Required: References to plans/specs (required for type: feature)\nspec_refs:\n  - docs/04-operations/plans/WU-XXX-plan.md\n\n# Required: Code files changed or created (empty only for docs/process WUs)\ncode_paths:\n  - path/to/file.ts\n\n# Required: Test paths (at least one of manual/unit/e2e/integration for non-doc WUs)\ntests:\n  manual:\n    - Manual test: Verify behavior\n  unit:\n    - path/to/test.test.ts\n  e2e: []\n  integration: []\n\n# Required: Exposure level\nexposure: 'backend-only' # ui | api | backend-only | documentation\n\n# Optional: User journey (recommended for ui/api)\n# user_journey: |\n#   User navigates to ...\n#   User performs ...\n\n# Optional: UI pairing WUs (for api exposure)\n# ui_pairing_wus:\n#   - WU-1234\n\n# Optional: Navigation path (required when exposure=ui and no page file)\n# navigation_path: '/settings'\n\n# Required: Deliverable artifacts (stamps, docs, etc.)\nartifacts:\n  - .lumenflow/stamps/WU-XXX.done\n\n# Optional: Dependencies (other WUs that must complete first)\ndependencies: []\n\n# Optional: Risks\nrisks:\n  - Risk 1\n\n# Optional: Notes\nnotes: ''\n\n# Optional: Requires human review\nrequires_review: false\n\n# Optional: Claimed mode (worktree or branch-only)\n# Automatically set by wu:claim, usually don't need to specify\n# claimed_mode: worktree\n\n# Optional: Assigned to (email of current claimant)\n# Automatically set by wu:claim\n# assigned_to: engineer@example.com\n\n# Optional: Locked status (prevents concurrent edits)\n# Automatically set by wu:claim and wu:done\n# locked: false\n\n# Optional: Completion date (ISO 8601 format)\n# Automatically set by wu:done\n# completed: 2025-10-23\n\n# Optional: Completion notes (added by wu:done)\n# completion_notes: |\n#   Additional notes added during wu:done.\n#   Any deviations from original plan.\n#   Lessons learned.\n\n# ============================================================================\n# GOVERNANCE BLOCK (WU Schema v2.0)\n# ============================================================================\n# Optional: COS governance rules that apply to this WU\n# Only include if this WU needs specific governance enforcement\n\n# governance:\n#   # Rules that apply to this WU (evaluated during cos:gates)\n#   rules:\n#     - rule_id: UPAIN-01\n#       satisfied: false  # Initially false, set true when evidence provided\n#       evidence:\n#         - type: link\n#           value: docs/product/voc/feature-user-pain.md\n#           description: "Voice of Customer analysis showing user pain"\n#       notes: |\n#         VOC analysis shows 40% of support tickets request this feature.\n#         Average time wasted: 15min/user/week.\n#\n#     - rule_id: CASH-03\n#       satisfied: false\n#       evidence:\n#         - type: link\n#           value: docs/finance/spend-reviews/2025-10-cloud-infra.md\n#           description: "Spend review for £1200/month cloud infrastructure"\n#         - type: approval\n#           value: owner@example.com\n#           description: "Owner approval for spend commitment"\n#       notes: |\n#         New cloud infrastructure commitment: £1200/month for 12 months.\n#         ROI: Reduces latency by 50%, improves user retention.\n#\n#   # Gate checks (enforced by cos-gates.mjs)\n#   gates:\n#     narrative: "pending"  # Status: pending, passed, skipped, failed\n#     finance: "pending"\n#\n#   # Exemptions (only if rule doesn't apply)\n#   exemptions:\n#     - rule_id: FAIR-01\n#       reason: "No user-facing pricing changes in this WU"\n#       approved_by: product-owner@example.com\n#       approved_at: 2025-10-23\n\n# ============================================================================\n# USAGE NOTES\n# ============================================================================\n#\n# 1. Remove this entire governance block if no COS rules apply to your WU\n# 2. Only include rules that require enforcement (not all rules apply to all WUs)\n# 3. Evidence types: link:, metric:, screenshot:, approval:\n# 4. Gates are checked during wu:done (before merge)\n# 5. Exemptions require approval from rule owner\n#\n# For more details, see:\n# - docs/04-operations/_frameworks/cos/system-prompt-v1.3.md\n# - docs/04-operations/_frameworks/cos/evidence-format.md\n`;

// Template for .lumenflow.framework.yaml
const FRAMEWORK_HINT_TEMPLATE = `# LumenFlow Framework Hint\n# Generated by: lumenflow init --framework {{FRAMEWORK_NAME}}\n\nframework: "{{FRAMEWORK_NAME}}"\nslug: "{{FRAMEWORK_SLUG}}"\n`;

// Template for docs/04-operations/_frameworks/<framework>/README.md
const FRAMEWORK_OVERLAY_TEMPLATE = `# {{FRAMEWORK_NAME}} Framework Overlay\n\n**Last updated:** {{DATE}}\n\nThis overlay captures framework-specific conventions, constraints, and references for {{FRAMEWORK_NAME}} projects.\n\n## Scope\n\n- Project structure conventions\n- Framework-specific testing guidance\n- Common pitfalls and mitigations\n\n## References\n\n- Add official docs links here\n`;

// WU-1083: Agent onboarding docs templates
const QUICK_REF_COMMANDS_TEMPLATE = `# Quick Reference: LumenFlow Commands

**Last updated:** {{DATE}}

---

## Project Setup

| Command                                       | Description                             |
| --------------------------------------------- | --------------------------------------- |
| \`pnpm exec lumenflow init\`                    | Scaffold minimal LumenFlow core         |
| \`pnpm exec lumenflow init --full\`             | Add docs/04-operations task scaffolding |
| \`pnpm exec lumenflow init --framework <name>\` | Add framework hint + overlay docs       |
| \`pnpm exec lumenflow init --force\`            | Overwrite existing files                |

---

## WU Management

| Command                                                                                                                                                                                                               | Description                                   |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------- |
| \`pnpm wu:create --id WU-XXX --lane <Lane> --title "Title" --description "..." --acceptance "..." --code-paths "path" --test-paths-unit "path" --exposure backend-only --spec-refs "~/.lumenflow/plans/WU-XXX.md"\` | Create new WU                                 |
| \`pnpm wu:claim --id WU-XXX --lane <Lane>\`                                                                                                                                                                             | Claim WU (creates worktree)                   |
| \`pnpm wu:done --id WU-XXX\`                                                                                                                                                                                            | Complete WU (merge, stamp, cleanup)           |
| \`pnpm wu:block --id WU-XXX --reason "Reason"\`                                                                                                                                                                         | Block a WU                                    |
| \`pnpm wu:unblock --id WU-XXX\`                                                                                                                                                                                         | Unblock a WU                                  |

---

## Gates

| Command                  | Description                |
| ------------------------ | -------------------------- |
| \`pnpm gates\`             | Run all quality gates      |
| \`pnpm gates --docs-only\` | Run gates for docs changes |
| \`pnpm format\`            | Format all files           |
| \`pnpm lint\`              | Run linter                 |
| \`pnpm typecheck\`         | Run TypeScript check       |
| \`pnpm test\`              | Run tests                  |

---

## Git (Safe Operations)

| Command                              | Description               |
| ------------------------------------ | ------------------------- |
| \`git status\`                         | Check working tree status |
| \`git add .\`                          | Stage all changes         |
| \`git commit -m "type: message"\`      | Commit with message       |
| \`git push origin lane/<lane>/wu-xxx\` | Push to remote            |

---

## Navigation

\`\`\`bash
# After claiming, go to worktree
cd worktrees/<lane>-wu-xxx

# Return to main for wu:done
cd /path/to/main
\`\`\`

---

## Workflow Sequence

\`\`\`bash
# 1. Create
pnpm wu:create --id WU-001 --lane "Framework: Core" --title "Add feature" \\
  --description "Context: ...\\nProblem: ...\\nSolution: ..." \\
  --acceptance "Criterion 1" --acceptance "Criterion 2" \\
  --code-paths "src/example.ts" \\
  --test-paths-unit "src/__tests__/example.test.ts" \\
  --exposure backend-only

# 2. Claim
pnpm wu:claim --id WU-001 --lane "Framework: Core"
cd worktrees/framework-core-wu-001

# 3. Work (TDD)
# ... write tests first, then code ...

# 4. Commit
git add .
git commit -m "feat: add feature"
git push origin lane/framework-core/wu-001

# 5. Gates
pnpm gates

# 6. Complete
cd /path/to/main
pnpm wu:done --id WU-001
\`\`\`

---

## File Paths

| Path                                      | Description          |
| ----------------------------------------- | -------------------- |
| \`docs/04-operations/tasks/wu/WU-XXX.yaml\` | WU specification     |
| \`docs/04-operations/tasks/status.md\`      | Current status board |
| \`.lumenflow/stamps/WU-XXX.done\`           | Completion stamp     |
| \`worktrees/<lane>-wu-xxx/\`                | Worktree directory   |
`;

const FIRST_WU_MISTAKES_TEMPLATE = `# First WU Mistakes

**Last updated:** {{DATE}}

Common mistakes agents make on their first WU, and how to avoid them.

---

## Mistake 1: Not Using Worktrees

### Wrong

\`\`\`bash
# Working directly in main
vim src/feature.ts
git commit -m "feat: add feature"
git push origin main
\`\`\`

### Right

\`\`\`bash
# Claim first, then work in worktree
pnpm wu:claim --id WU-123 --lane Core
cd worktrees/core-wu-123
vim src/feature.ts
git commit -m "feat: add feature"
git push origin lane/core/wu-123
cd /path/to/main
pnpm wu:done --id WU-123
\`\`\`

---

## Mistake 2: Forgetting to Run wu:done

See [troubleshooting-wu-done.md](troubleshooting-wu-done.md) for the full explanation.

**TL;DR:** After gates pass, ALWAYS run \`pnpm wu:done --id WU-XXX\`.

---

## Mistake 3: Working Outside code_paths

### Wrong

The WU says \`code_paths: [src/api/**]\` but you edit \`src/ui/component.ts\`.

### Right

Only edit files within the specified \`code_paths\`. If you need to edit other files, that's a different WU.

---

## Mistake 4: Skipping TDD

### Wrong

\`\`\`
1. Write the feature
2. Maybe write tests later
3. Tests are hard, skip them
\`\`\`

### Right

\`\`\`
1. Write failing test
2. Run test (confirm RED)
3. Write minimum code
4. Run test (confirm GREEN)
5. Refactor if needed
\`\`\`

---

## Mistake 5: Using Forbidden Git Commands

### Wrong

\`\`\`bash
git reset --hard HEAD
git push --force
git commit --no-verify
\`\`\`

### Right

\`\`\`bash
git add .
git commit -m "feat: description"
git push origin lane/core/wu-123
\`\`\`

---

## Mistake 6: Ignoring Gate Failures

### Wrong

\`\`\`
Gates failed but I think the code is fine.
Let me use --skip-gates.
\`\`\`

### Right

\`\`\`
Gates failed. Let me read the error:
- TypeScript error in src/api/handler.ts
- Missing return type

Fix: Add the return type.
Re-run: pnpm gates
\`\`\`

---

## Quick Checklist

Before starting any WU:

- [ ] Read the full WU spec
- [ ] Understand acceptance criteria
- [ ] Claim the WU with \`pnpm wu:claim\`
- [ ] cd to the worktree IMMEDIATELY
- [ ] Work only in the worktree
- [ ] Stay within code_paths
- [ ] Follow TDD
- [ ] Run gates before wu:done
- [ ] ALWAYS run wu:done
`;

const TROUBLESHOOTING_WU_DONE_TEMPLATE = `# Troubleshooting: wu:done Not Run

**Last updated:** {{DATE}}

This is the most common mistake agents make. This document explains why it happens and how to fix it.

---

## The Problem

Agents complete their work, write "To Complete: pnpm wu:done --id WU-XXX" in their response, and then **stop without actually running the command**.

### Why This Happens

1. **Confusion about scope**: Agent thinks completion is a "next step" for the human
2. **Fear of overstepping**: Agent hesitates to take "final" actions
3. **Missing context**: Agent doesn't realize wu:done is expected to be run immediately
4. **Token limits**: Agent runs out of context and summarizes remaining steps

---

## The Fix

### Rule: ALWAYS Run wu:done

After gates pass, you MUST run:

\`\`\`bash
cd /path/to/main
pnpm wu:done --id WU-XXX
\`\`\`

Do NOT:

- Ask "Should I run wu:done?"
- Write "To Complete: pnpm wu:done"
- Wait for permission
- Treat it as a "future step"

---

## Correct Completion Flow

\`\`\`bash
# 1. In worktree, run gates
pnpm gates

# 2. If gates pass, return to main
cd /path/to/main

# 3. IMMEDIATELY run wu:done
pnpm wu:done --id WU-XXX

# 4. Report success with the wu:done output
\`\`\`

---

## What wu:done Does

When you run \`pnpm wu:done --id WU-XXX\`:

1. Validates the worktree exists and has commits
2. Runs gates in the worktree (not main)
3. Fast-forward merges to main
4. Creates the done stamp
5. Updates status and backlog docs
6. Removes the worktree
7. Pushes to origin

**This is the ONLY way to complete a WU.** Manual steps will leave things in an inconsistent state.

---

## Symptoms of Incomplete WU

If wu:done wasn't run, you'll see:

- Worktree still exists: \`ls worktrees/\`
- No stamp: \`ls .lumenflow/stamps/WU-XXX.done\` returns nothing
- Status unchanged: WU still shows as \`in_progress\`
- Branch not merged: Changes only on lane branch

---

## Recovery

If a previous agent forgot to run wu:done:

\`\`\`bash
# 1. Check worktree exists
ls worktrees/

# 2. If it does, run wu:done
pnpm wu:done --id WU-XXX
\`\`\`

---

## Checklist Before Ending Session

- [ ] Did I run \`pnpm gates\` in the worktree?
- [ ] Did gates pass?
- [ ] Did I \`cd\` back to main?
- [ ] Did I run \`pnpm wu:done --id WU-XXX\`?
- [ ] Did wu:done complete successfully?

If any answer is "no", you're not done yet.
`;

const AGENT_SAFETY_CARD_TEMPLATE = `# Agent Safety Card

**Last updated:** {{DATE}}

Quick reference for AI agents working in LumenFlow projects.

---

## Stop and Ask When

- Same error repeats 3 times
- Auth or permissions changes needed
- PII/PHI/secrets involved
- Cloud spend decisions
- Policy changes required
- Anything feels irreversible

---

## Never Do

| Action                   | Why              |
| ------------------------ | ---------------- |
| \`git reset --hard\`       | Data loss        |
| \`git push --force\`       | History rewrite  |
| \`--no-verify\`            | Bypasses safety  |
| \`git stash\` (on main)    | Hides work       |
| \`git clean -fd\`          | Deletes files    |
| Work in main after claim | Breaks isolation |
| Skip wu:done             | Incomplete WU    |

---

## Always Do

| Action                     | Why              |
| -------------------------- | ---------------- |
| Read WU spec first         | Understand scope |
| cd to worktree after claim | Isolation        |
| Write tests before code    | TDD              |
| Run gates before wu:done   | Quality          |
| Run wu:done                | Complete WU      |
| Stay within code_paths     | Scope discipline |

---

## Error Handling

### Max 3 Attempts

If same error happens 3 times:

1. Stop trying
2. Document what happened
3. Ask for help

### Gate Failures

1. Read the error message
2. Fix the underlying issue
3. Re-run gates
4. Never use \`--skip-gates\` for new failures

---

## Quick Commands

\`\`\`bash
# Check lane availability
cat docs/04-operations/tasks/status.md

# Claim a WU
pnpm wu:claim --id WU-XXX --lane <Lane>

# Work in worktree
cd worktrees/<lane>-wu-xxx

# Run gates
pnpm gates          # Code changes
pnpm gates --docs-only  # Docs changes

# Complete WU
cd /path/to/main
pnpm wu:done --id WU-XXX
\`\`\`

---

## Completion Checklist

- [ ] Gates pass
- [ ] cd to main
- [ ] Run wu:done
- [ ] Verify success output
- [ ] Report completion

---

## When Uncertain

Choose the safer path:

- Don't modify files outside code_paths
- Don't bypass hooks
- Don't skip gates
- Ask rather than assume
`;

const WU_CREATE_CHECKLIST_TEMPLATE = `# WU Creation Checklist

**Last updated:** {{DATE}}

Before running \`pnpm wu:create\`, verify these items.

---

## Step 1: Check Valid Lanes

\`\`\`bash
grep -A 30 "lanes:" .lumenflow.config.yaml
\`\`\`

**Format:** \`"Parent: Sublane"\` (colon + single space)

Examples:
- \`"Framework: CLI"\`
- \`"Framework: Core"\`
- \`"Operations: CI/CD"\`
- \`"Content: Documentation"\`

---

## Step 2: Required Fields

| Field | Required For | Example |
|-------|--------------|---------|
| \`--id\` | All | \`WU-1234\` |
| \`--lane\` | All | \`"Experience: Chat"\` |
| \`--title\` | All | \`"Add feature"\` |
| \`--description\` | All | \`"Context: ... Problem: ... Solution: ..."\` |
| \`--acceptance\` | All | \`--acceptance "Works"\` (repeatable) |
| \`--exposure\` | All | \`ui\`, \`api\`, \`backend-only\`, \`documentation\` |
| \`--code-paths\` | Code WUs | \`"src/a.ts,src/b.ts"\` |
| \`--test-paths-unit\` | Code WUs | \`"src/__tests__/a.test.ts"\` |
| \`--spec-refs\` | Feature WUs | \`"~/.lumenflow/plans/WU-XXX.md"\` |

---

## Step 3: Plan Storage

Plans go in \`~/.lumenflow/plans/\` (NOT in project):

\`\`\`bash
mkdir -p ~/.lumenflow/plans
# Create your plan
vim ~/.lumenflow/plans/WU-XXX-plan.md
\`\`\`

Reference in wu:create:
\`\`\`bash
--spec-refs "~/.lumenflow/plans/WU-XXX-plan.md"
\`\`\`

---

## Step 4: Validate First

\`\`\`bash
pnpm wu:create --id WU-XXX ... --validate
\`\`\`

Fix errors, then remove \`--validate\` to create.

---

## Complete Example

\`\`\`bash
pnpm wu:create \\
  --id WU-1234 \\
  --lane "Framework: CLI" \\
  --title "Add feature X" \\
  --description "Context: Users need X. Problem: X doesn't exist. Solution: Add X." \\
  --acceptance "Feature X works as specified" \\
  --acceptance "Unit tests pass with >90% coverage" \\
  --code-paths "packages/@lumenflow/cli/src/x.ts" \\
  --test-paths-unit "packages/@lumenflow/cli/__tests__/x.test.ts" \\
  --exposure backend-only \\
  --spec-refs "~/.lumenflow/plans/WU-1234-plan.md"
\`\`\`

---

## Common Errors

### "Lane format invalid"

**Cause:** Missing colon or space in lane format.

**Fix:** Use \`"Parent: Sublane"\` format (colon + space).

### "Missing required field"

**Cause:** Required field not provided.

**Fix:** Add the missing \`--field\` argument.

### "WU already exists"

**Cause:** WU with this ID already exists.

**Fix:** Use a different ID or check existing WUs.

---

## After Creation

1. Review the created YAML: \`cat docs/04-operations/tasks/wu/WU-XXX.yaml\`
2. Claim the WU: \`pnpm wu:claim --id WU-XXX --lane "Lane"\`
3. cd to worktree: \`cd worktrees/<lane>-wu-xxx\`
`;

// WU-1083: Claude skills templates
const WU_LIFECYCLE_SKILL_TEMPLATE = `---
name: wu-lifecycle
description: Work Unit claim/block/done workflow automation.
version: 1.0.0
---

# WU Lifecycle Skill

## When to Use

Activate this skill when:

- Claiming a WU (\`pnpm wu:claim\`)
- Blocking/unblocking WUs due to dependencies
- Running \`wu:done\` completion workflow
- Understanding WU state machine transitions

## State Machine

\`\`\`
ready -> in_progress -> waiting/blocked -> done
\`\`\`

## Core Commands

\`\`\`bash
# Claim WU
pnpm wu:claim --id WU-XXX --lane <lane>
cd worktrees/<lane>-wu-xxx   # IMMEDIATELY

# Complete WU (from main)
cd ../..
pnpm wu:done --id WU-XXX

# Block/Unblock
pnpm wu:block --id WU-XXX --reason "..."
pnpm wu:unblock --id WU-XXX

# Create (full spec)
pnpm wu:create --id WU-999 --lane "Operations" --title "Add feature" \\
  --description "Context: ... Problem: ... Solution: ..." \\
  --acceptance "Feature works" --code-paths "src/a.ts" --validate
\`\`\`

## wu:done Workflow

1. Runs gates in worktree
2. Fast-forward merge to main
3. Creates \`.lumenflow/stamps/WU-XXX.done\`
4. Updates backlog.md + status.md
5. Removes worktree

## Worktree Discipline

After \`wu:claim\`:

- \`cd worktrees/<lane>-wu-xxx\` immediately
- Use relative paths (never absolute)
- Main is read-only
`;

const WORKTREE_DISCIPLINE_SKILL_TEMPLATE = `---
name: worktree-discipline
description: Prevents the "absolute path trap" in Write/Edit/Read tools.
version: 1.0.0
---

# Worktree Discipline: Absolute Path Trap Prevention

**Purpose**: Prevent AI agents from bypassing worktree isolation via absolute file paths.

## The Absolute Path Trap

**Problem**: AI agents using Write/Edit/Read tools can bypass worktree isolation by passing absolute paths. Even when your shell is in the worktree, absolute paths target the main checkout.

### Example

\`\`\`typescript
// Shell: cd worktrees/operations-wu-427

// WRONG - Absolute path bypasses worktree
Write({
  file_path: '/home/user/source/project/apps/web/src/validator.ts',
  content: '...',
});
// Result: Written to MAIN checkout, not worktree!

// RIGHT - Relative path respects worktree
Write({
  file_path: 'apps/web/src/validator.ts',
  content: '...',
});
// Result: Written to worktree correctly
\`\`\`

## Pre-Operation Checklist

**Before ANY Write/Edit/Read operation:**

1. **Verify working directory**:

   \`\`\`bash
   pwd
   # Must show: .../worktrees/<lane>-wu-xxx
   \`\`\`

2. **Check file path format**:

   | Pattern                           | Safe? | Example                  |
   | --------------------------------- | ----- | ------------------------ |
   | Starts with \`/home/\` or \`/Users/\` | NO    | \`/home/user/.../file.ts\` |
   | Contains full repo path           | NO    | \`/source/project/...\`    |
   | Starts with package name          | YES   | \`apps/web/src/...\`       |
   | Starts with \`./\` or \`../\`         | YES   | \`./src/lib/...\`          |
   | Just filename                     | YES   | \`README.md\`              |

3. **Use relative paths for ALL file operations**

## Golden Rules

1. **Always verify pwd** before file operations
2. **Never use absolute paths** in Write/Edit/Read tools
3. **When in doubt, use relative paths**
`;

const LUMENFLOW_GATES_SKILL_TEMPLATE = `---
name: lumenflow-gates
description: Quality gates troubleshooting (format, lint, typecheck, tests).
version: 1.0.0
---

# LumenFlow Gates Skill

## When to Use

Activate this skill when:

- \`pnpm gates\` fails with format, lint, or typecheck errors
- Need to determine if failure is from your changes vs pre-existing
- Debugging test failures or coverage issues
- Deciding whether to use \`--skip-gates\` (emergency only)

## Gate Sequence

\`\`\`
pnpm gates = format:check -> lint -> typecheck -> spec:linter -> tests
\`\`\`

## Fix Patterns

| Gate      | Auto-fix        | Manual                              |
| --------- | --------------- | ----------------------------------- |
| Format    | \`pnpm format\`   | -                                   |
| Lint      | \`pnpm lint:fix\` | Fix reported issues                 |
| Typecheck | -               | Fix type errors (first error first) |
| Tests     | -               | Debug, fix mocks, update snapshots  |

## Decision Tree

**Gate failed. Is it from YOUR changes?**

\`\`\`bash
git checkout main && pnpm gates  # Check main
# Pass on main -> Your change caused it -> Fix it
# Fail on main -> Pre-existing -> Consider --skip-gates
\`\`\`

**Can you fix it?**

- In your \`code_paths\`, <=10 lines -> Fix in place
- Different paths, >10 lines -> Create Bug WU

## Skip Gates (Emergency)

Only when pre-existing failures:

\`\`\`bash
pnpm wu:done --id WU-XXX --skip-gates --reason "Pre-existing" --fix-wu WU-YYY
\`\`\`

## Common Lint Fixes

\`\`\`
no-explicit-any -> Add proper types
no-unused-vars -> Remove or prefix with _
no-restricted-paths -> Check hex boundaries
exhaustive-deps -> Add missing dependencies
\`\`\`

## Validation Commands

\`\`\`bash
pnpm gates                # All gates
pnpm gates -- --docs-only # Docs WUs
pnpm format               # Fix formatting
pnpm lint:fix             # Fix lint issues
pnpm typecheck            # Check types
\`\`\`
`;

/**
 * Detect default client from environment
 */
function detectDefaultClient(): DefaultClient {
  if (process.env.CLAUDE_PROJECT_DIR || process.env.CLAUDE_CODE) {
    return 'claude-code';
  }
  return 'none';
}

/**
 * Parse vendor flag from arguments
 */
function parseVendorArg(args: string[]): VendorType | undefined {
  const vendorIndex = args.findIndex((arg) => arg === '--vendor');
  if (vendorIndex !== -1 && args[vendorIndex + 1]) {
    const vendor = args[vendorIndex + 1].toLowerCase();
    if (['claude', 'cursor', 'aider', 'all', 'none'].includes(vendor)) {
      return vendor as VendorType;
    }
  }
  return undefined;
}

/**
 * Parse framework flag from arguments
 */
function parseFrameworkArg(args: string[]): string | undefined {
  const frameworkArg = args.find((arg) => arg.startsWith('--framework='));
  if (frameworkArg) {
    const [, value] = frameworkArg.split('=', 2);
    return value?.trim() || undefined;
  }

  const frameworkIndex = args.findIndex((arg) => arg === '--framework');
  if (frameworkIndex !== -1 && args[frameworkIndex + 1]) {
    return args[frameworkIndex + 1];
  }

  return undefined;
}

/**
 * WU-1067: Parse --preset flag from arguments for config-driven gates
 */
function parsePresetArg(args: string[]): GatePresetType | undefined {
  const presetArg = args.find((arg) => arg.startsWith('--preset='));
  if (presetArg) {
    const [, value] = presetArg.split('=', 2);
    const preset = value?.trim().toLowerCase();
    if (preset && ['node', 'python', 'go', 'rust', 'dotnet'].includes(preset)) {
      return preset as GatePresetType;
    }
    return undefined;
  }

  const presetIndex = args.findIndex((arg) => arg === '--preset');
  if (presetIndex !== -1 && args[presetIndex + 1]) {
    const preset = args[presetIndex + 1].toLowerCase();
    if (['node', 'python', 'go', 'rust', 'dotnet'].includes(preset)) {
      return preset as GatePresetType;
    }
  }

  return undefined;
}

function shouldUseVendor(vendor: VendorType | undefined, defaultClient: DefaultClient): VendorType {
  if (vendor) {
    return vendor;
  }
  return defaultClient === 'claude-code' ? 'claude' : 'none';
}

/**
 * Scaffold a new LumenFlow project
 */
export async function scaffoldProject(
  targetDir: string,
  options: ScaffoldOptions,
): Promise<ScaffoldResult> {
  const result: ScaffoldResult = {
    created: [],
    skipped: [],
  };

  const defaultClient = options.defaultClient ?? detectDefaultClient();
  const vendor = shouldUseVendor(options.vendor, defaultClient);

  // Ensure target directory exists
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const tokenDefaults = {
    DATE: getCurrentDate(),
    PROJECT_ROOT: targetDir,
  };

  // Create .lumenflow.config.yaml (WU-1067: includes gate preset if specified)
  await createFile(
    path.join(targetDir, CONFIG_FILE_NAME),
    generateLumenflowConfigYaml(options.gatePreset),
    options.force,
    result,
    targetDir,
  );

  // Create LUMENFLOW.md (main entry point)
  await createFile(
    path.join(targetDir, 'LUMENFLOW.md'),
    processTemplate(LUMENFLOW_MD_TEMPLATE, tokenDefaults),
    options.force,
    result,
    targetDir,
  );

  // Create .lumenflow/constraints.md
  await createFile(
    path.join(targetDir, LUMENFLOW_DIR, 'constraints.md'),
    processTemplate(CONSTRAINTS_MD_TEMPLATE, tokenDefaults),
    options.force,
    result,
    targetDir,
  );

  // Create .lumenflow/agents directory with .gitkeep
  await createDirectory(path.join(targetDir, LUMENFLOW_AGENTS_DIR), result, targetDir);
  await createFile(
    path.join(targetDir, LUMENFLOW_AGENTS_DIR, '.gitkeep'),
    '',
    options.force,
    result,
    targetDir,
  );

  // Optional: full docs scaffolding
  if (options.full) {
    await scaffoldFullDocs(targetDir, options, result, tokenDefaults);
  }

  // Optional: framework overlay
  if (options.framework) {
    await scaffoldFrameworkOverlay(targetDir, options, result, tokenDefaults);
  }

  // Scaffold vendor-specific files
  await scaffoldVendorFiles(targetDir, options, result, tokenDefaults, vendor);

  return result;
}

async function scaffoldFullDocs(
  targetDir: string,
  options: ScaffoldOptions,
  result: ScaffoldResult,
  tokens: Record<string, string>,
): Promise<void> {
  const tasksDir = path.join(targetDir, 'docs', '04-operations', 'tasks');
  const wuDir = path.join(tasksDir, 'wu');
  const templatesDir = path.join(tasksDir, 'templates');

  await createDirectory(wuDir, result, targetDir);
  await createDirectory(templatesDir, result, targetDir);
  await createFile(path.join(wuDir, '.gitkeep'), '', options.force, result, targetDir);

  await createFile(
    path.join(tasksDir, 'backlog.md'),
    BACKLOG_TEMPLATE,
    options.force,
    result,
    targetDir,
  );

  await createFile(
    path.join(tasksDir, 'status.md'),
    STATUS_TEMPLATE,
    options.force,
    result,
    targetDir,
  );

  await createFile(
    path.join(templatesDir, 'wu-template.yaml'),
    processTemplate(WU_TEMPLATE_YAML, tokens),
    options.force,
    result,
    targetDir,
  );

  // WU-1083: Scaffold agent onboarding docs with --full
  await scaffoldAgentOnboardingDocs(targetDir, options, result, tokens);
}

/**
 * WU-1083: Scaffold agent onboarding documentation
 */
async function scaffoldAgentOnboardingDocs(
  targetDir: string,
  options: ScaffoldOptions,
  result: ScaffoldResult,
  tokens: Record<string, string>,
): Promise<void> {
  const onboardingDir = path.join(
    targetDir,
    'docs',
    '04-operations',
    '_frameworks',
    'lumenflow',
    'agent',
    'onboarding',
  );

  await createDirectory(onboardingDir, result, targetDir);

  await createFile(
    path.join(onboardingDir, 'quick-ref-commands.md'),
    processTemplate(QUICK_REF_COMMANDS_TEMPLATE, tokens),
    options.force,
    result,
    targetDir,
  );

  await createFile(
    path.join(onboardingDir, 'first-wu-mistakes.md'),
    processTemplate(FIRST_WU_MISTAKES_TEMPLATE, tokens),
    options.force,
    result,
    targetDir,
  );

  await createFile(
    path.join(onboardingDir, 'troubleshooting-wu-done.md'),
    processTemplate(TROUBLESHOOTING_WU_DONE_TEMPLATE, tokens),
    options.force,
    result,
    targetDir,
  );

  await createFile(
    path.join(onboardingDir, 'agent-safety-card.md'),
    processTemplate(AGENT_SAFETY_CARD_TEMPLATE, tokens),
    options.force,
    result,
    targetDir,
  );

  await createFile(
    path.join(onboardingDir, 'wu-create-checklist.md'),
    processTemplate(WU_CREATE_CHECKLIST_TEMPLATE, tokens),
    options.force,
    result,
    targetDir,
  );
}

/**
 * WU-1083: Scaffold Claude skills
 */
async function scaffoldClaudeSkills(
  targetDir: string,
  options: ScaffoldOptions,
  result: ScaffoldResult,
  tokens: Record<string, string>,
): Promise<void> {
  const skillsDir = path.join(targetDir, '.claude', 'skills');

  // wu-lifecycle skill
  const wuLifecycleDir = path.join(skillsDir, 'wu-lifecycle');
  await createDirectory(wuLifecycleDir, result, targetDir);
  await createFile(
    path.join(wuLifecycleDir, 'SKILL.md'),
    processTemplate(WU_LIFECYCLE_SKILL_TEMPLATE, tokens),
    options.force,
    result,
    targetDir,
  );

  // worktree-discipline skill
  const worktreeDir = path.join(skillsDir, 'worktree-discipline');
  await createDirectory(worktreeDir, result, targetDir);
  await createFile(
    path.join(worktreeDir, 'SKILL.md'),
    processTemplate(WORKTREE_DISCIPLINE_SKILL_TEMPLATE, tokens),
    options.force,
    result,
    targetDir,
  );

  // lumenflow-gates skill
  const gatesDir = path.join(skillsDir, 'lumenflow-gates');
  await createDirectory(gatesDir, result, targetDir);
  await createFile(
    path.join(gatesDir, 'SKILL.md'),
    processTemplate(LUMENFLOW_GATES_SKILL_TEMPLATE, tokens),
    options.force,
    result,
    targetDir,
  );
}

async function scaffoldFrameworkOverlay(
  targetDir: string,
  options: ScaffoldOptions,
  result: ScaffoldResult,
  tokens: Record<string, string>,
): Promise<void> {
  if (!options.framework) {
    return;
  }

  const { name, slug } = normalizeFrameworkName(options.framework);
  const frameworkTokens = {
    ...tokens,
    FRAMEWORK_NAME: name,
    FRAMEWORK_SLUG: slug,
  };

  await createFile(
    path.join(targetDir, FRAMEWORK_HINT_FILE),
    processTemplate(FRAMEWORK_HINT_TEMPLATE, frameworkTokens),
    options.force,
    result,
    targetDir,
  );

  const overlayDir = path.join(targetDir, 'docs', '04-operations', '_frameworks', slug);
  await createDirectory(overlayDir, result, targetDir);

  await createFile(
    path.join(overlayDir, 'README.md'),
    processTemplate(FRAMEWORK_OVERLAY_TEMPLATE, frameworkTokens),
    options.force,
    result,
    targetDir,
  );
}

/**
 * Scaffold vendor-specific files based on --vendor option
 */
async function scaffoldVendorFiles(
  targetDir: string,
  options: ScaffoldOptions,
  result: ScaffoldResult,
  tokens: Record<string, string>,
  vendor: VendorType,
): Promise<void> {
  // Claude Code
  if (vendor === 'claude' || vendor === 'all') {
    await createFile(
      path.join(targetDir, 'CLAUDE.md'),
      processTemplate(CLAUDE_MD_TEMPLATE, tokens),
      options.force,
      result,
      targetDir,
    );

    await createDirectory(path.join(targetDir, CLAUDE_AGENTS_DIR), result, targetDir);
    await createFile(
      path.join(targetDir, CLAUDE_AGENTS_DIR, '.gitkeep'),
      '',
      options.force,
      result,
      targetDir,
    );

    await createFile(
      path.join(targetDir, CLAUDE_DIR, 'settings.json'),
      CLAUDE_SETTINGS_TEMPLATE,
      options.force,
      result,
      targetDir,
    );

    // WU-1083: Scaffold Claude skills
    await scaffoldClaudeSkills(targetDir, options, result, tokens);

    // WU-1083: Scaffold agent onboarding docs for Claude vendor (even without --full)
    await scaffoldAgentOnboardingDocs(targetDir, options, result, tokens);
  }

  // Cursor
  if (vendor === 'cursor' || vendor === 'all') {
    const cursorDir = path.join(targetDir, '.cursor');
    await createDirectory(cursorDir, result, targetDir);
    await createFile(
      path.join(cursorDir, 'rules.md'),
      processTemplate(CURSOR_RULES_TEMPLATE, tokens),
      options.force,
      result,
      targetDir,
    );
  }

  // Aider
  if (vendor === 'aider' || vendor === 'all') {
    await createFile(
      path.join(targetDir, '.aider.conf.yml'),
      AIDER_CONF_TEMPLATE,
      options.force,
      result,
      targetDir,
    );
  }
}

/**
 * Create a directory if missing
 */
async function createDirectory(
  dirPath: string,
  result: ScaffoldResult,
  targetDir: string,
): Promise<void> {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
    result.created.push(getRelativePath(targetDir, dirPath));
  }
}

/**
 * Create a file, respecting force option
 */
async function createFile(
  filePath: string,
  content: string,
  force: boolean,
  result: ScaffoldResult,
  targetDir: string,
): Promise<void> {
  const relativePath = getRelativePath(targetDir, filePath);

  if (fs.existsSync(filePath) && !force) {
    result.skipped.push(relativePath);
    return;
  }

  const parentDir = path.dirname(filePath);
  if (!fs.existsSync(parentDir)) {
    fs.mkdirSync(parentDir, { recursive: true });
  }

  fs.writeFileSync(filePath, content);
  result.created.push(relativePath);
}

/**
 * CLI entry point
 * WU-1085: Updated to use parseInitOptions for proper --help support
 */
export async function main(): Promise<void> {
  const opts = parseInitOptions();
  const targetDir = process.cwd();

  console.log('[lumenflow init] Scaffolding LumenFlow project...');
  console.log(`  Mode: ${opts.full ? 'full' : 'minimal'}`);
  console.log(`  Framework: ${opts.framework ?? 'none'}`);
  console.log(`  Vendor overlays: ${opts.vendor ?? 'auto'}`);
  console.log(`  Gate preset: ${opts.preset ?? 'none (manual config)'}`);

  const result = await scaffoldProject(targetDir, {
    force: opts.force,
    full: opts.full,
    vendor: opts.vendor,
    framework: opts.framework,
    gatePreset: opts.preset,
  });

  if (result.created.length > 0) {
    console.log('\nCreated:');
    result.created.forEach((f) => console.log(`  + ${f}`));
  }

  if (result.skipped.length > 0) {
    console.log('\nSkipped (already exists, use --force to overwrite):');
    result.skipped.forEach((f) => console.log(`  - ${f}`));
  }

  console.log('\n[lumenflow init] Done! Next steps:');
  console.log('  1. Review LUMENFLOW.md for workflow documentation');
  console.log(`  2. Edit ${CONFIG_FILE_NAME} to match your project structure`);
  console.log('  3. Run: pnpm wu:create --id WU-0001 --lane <lane> --title "First WU"');
}
