/**
 * @file init.ts
 * LumenFlow project scaffolding command (WU-1005)
 * WU-1006: Library-First - use js-yaml.dump() for YAML generation
 *
 * Scaffolds new projects with:
 * - .lumenflow.yaml configuration
 * - CLAUDE.md development guide
 * - AGENTS.md agent context
 * - .beacon/stamps directory
 * - docs/04-operations/tasks/wu directory
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import yaml from 'js-yaml';

export interface ScaffoldOptions {
  force: boolean;
}

export interface ScaffoldResult {
  created: string[];
  skipped: string[];
}

/**
 * Default LumenFlow configuration object
 * WU-1006: Use structured object + js-yaml instead of string template
 */
const DEFAULT_LUMENFLOW_CONFIG = {
  version: '1.0',
  lanes: [
    { name: 'Core', paths: ['src/core/**'] },
    { name: 'API', paths: ['src/api/**'] },
    { name: 'UI', paths: ['src/ui/**', 'src/components/**'] },
    { name: 'Infrastructure', paths: ['infra/**', '.github/**'] },
    { name: 'Documentation', paths: ['docs/**', '*.md'] },
  ],
  gates: {
    format: true,
    lint: true,
    typecheck: true,
    test: true,
  },
  memory: {
    checkpoint_interval: 30,
  },
};

/**
 * Generate YAML configuration with header comment
 */
function generateLumenflowYaml(): string {
  const header = `# LumenFlow Configuration
# Generated by: lumenflow init
# Customize lanes based on your project structure

`;
  return header + yaml.dump(DEFAULT_LUMENFLOW_CONFIG, { lineWidth: -1, quotingType: "'" });
}

// Template for CLAUDE.md
const CLAUDE_MD_TEMPLATE = `# Development Guide

**Last updated:** ${new Date().toISOString().split('T')[0]}

This project uses LumenFlow workflow for all changes.

---

## Quick Start

\`\`\`bash
# 1. Create a WU
pnpm wu:create --id WU-XXXX --lane <Lane> --title "Title"

# 2. Edit WU spec with acceptance criteria, then claim:
pnpm wu:claim --id WU-XXXX --lane <Lane>
cd worktrees/<lane>-wu-xxxx

# 3. Implement in worktree

# 4. Run gates
pnpm gates

# 5. Complete (from main)
cd /path/to/main
pnpm wu:done --id WU-XXXX
\`\`\`

---

## Core Principles

1. **TDD**: Failing test → implementation → passing test (≥90% coverage on new code)
2. **Library-First**: Search existing libraries before custom code
3. **DRY/SOLID/KISS/YAGNI**: No magic numbers, no hardcoded strings
4. **Worktree Discipline**: After \`wu:claim\`, work ONLY in the worktree
5. **Gates Before Done**: All gates must pass before \`wu:done\`
6. **Do Not Bypass Hooks**: No \`--no-verify\`, fix issues properly

---

## Definition of Done

- Acceptance criteria satisfied
- Gates green (\`pnpm gates\`)
- WU YAML status = \`done\`
- \`.beacon/stamps/WU-<id>.done\` exists

---

## Commands Reference

| Command               | Description                         |
| --------------------- | ----------------------------------- |
| \`pnpm wu:create\`    | Create new WU spec                  |
| \`pnpm wu:claim\`     | Claim WU and create worktree        |
| \`pnpm wu:done\`      | Complete WU (merge, stamp, cleanup) |
| \`pnpm gates\`        | Run quality gates                   |
| \`pnpm mem:checkpoint\` | Save memory checkpoint            |
`;

// Template for AGENTS.md
const AGENTS_MD_TEMPLATE = `# Agent Context

This project uses LumenFlow workflow. Before starting any work:

## Context Loading Protocol

1. Read \`CLAUDE.md\` for workflow fundamentals
2. Read \`README.md\` for project structure
3. Read the specific WU YAML file from \`docs/04-operations/tasks/wu/\`

## Critical Rules

### Worktree Discipline (IMMUTABLE LAW)

After claiming a WU, you MUST work in its worktree:

\`\`\`bash
# 1. Claim creates worktree
pnpm wu:claim --id WU-XXX --lane <lane>

# 2. IMMEDIATELY cd to worktree
cd worktrees/<lane>-wu-xxx

# 3. ALL work happens here (edits, git add/commit/push, tests, gates)

# 4. Return to main ONLY to complete
cd ../../
pnpm wu:done --id WU-XXX
\`\`\`

Main checkout becomes read-only after claim. Hooks will block WU commits from main.

### Never Bypass Hooks

If a git hook fails (pre-commit, commit-msg):

1. Read the error message (shows which gate failed)
2. Fix the underlying issue (format/lint/type errors)
3. Re-run the commit

**NEVER use \`--no-verify\` or \`--no-gpg-sign\` to bypass hooks.**

### WIP = 1 Per Lane

Only ONE work unit can be "in progress" per lane at any time.

## Coding Standards

- **TDD:** Tests first, ≥90% coverage on new application code
- **Conventional commits:** \`type: summary\` (e.g., \`feat: add feature\`, \`fix: resolve bug\`)
- **Documentation:** Concise, clear Markdown

## Forbidden Git Commands (NEVER RUN on main)

\`\`\`bash
git reset --hard         # Data loss
git stash                # Hides work
git clean -fd            # Deletes files
git push --force         # History rewrite
--no-verify              # Bypasses safety checks
\`\`\`

**Where allowed:** Inside your worktree on a lane branch (safe, isolated).
`;

/**
 * Scaffold a new LumenFlow project
 */
export async function scaffoldProject(
  targetDir: string,
  options: ScaffoldOptions,
): Promise<ScaffoldResult> {
  const result: ScaffoldResult = {
    created: [],
    skipped: [],
  };

  // Ensure target directory exists
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  // Create .lumenflow.yaml (WU-1006: use js-yaml.dump() instead of string template)
  await createFile(
    path.join(targetDir, '.lumenflow.yaml'),
    generateLumenflowYaml(),
    options.force,
    result,
  );

  // Create CLAUDE.md
  await createFile(path.join(targetDir, 'CLAUDE.md'), CLAUDE_MD_TEMPLATE, options.force, result);

  // Create AGENTS.md
  await createFile(path.join(targetDir, 'AGENTS.md'), AGENTS_MD_TEMPLATE, options.force, result);

  // Create .beacon/stamps directory
  const beaconStampsDir = path.join(targetDir, '.beacon', 'stamps');
  if (!fs.existsSync(beaconStampsDir)) {
    fs.mkdirSync(beaconStampsDir, { recursive: true });
    result.created.push('.beacon/stamps');
  }

  // Create docs/04-operations/tasks/wu directory with .gitkeep
  const wuDir = path.join(targetDir, 'docs', '04-operations', 'tasks', 'wu');
  if (!fs.existsSync(wuDir)) {
    fs.mkdirSync(wuDir, { recursive: true });
    result.created.push('docs/04-operations/tasks/wu');
  }

  // Create .gitkeep in WU directory
  const gitkeepPath = path.join(wuDir, '.gitkeep');
  if (!fs.existsSync(gitkeepPath)) {
    fs.writeFileSync(gitkeepPath, '');
  }

  return result;
}

/**
 * Create a file, respecting force option
 */
async function createFile(
  filePath: string,
  content: string,
  force: boolean,
  result: ScaffoldResult,
): Promise<void> {
  const relativePath = path.basename(filePath);

  if (fs.existsSync(filePath) && !force) {
    result.skipped.push(relativePath);
    return;
  }

  // Ensure parent directory exists
  const parentDir = path.dirname(filePath);
  if (!fs.existsSync(parentDir)) {
    fs.mkdirSync(parentDir, { recursive: true });
  }

  fs.writeFileSync(filePath, content);
  result.created.push(relativePath);
}

/**
 * CLI entry point
 */
export async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const force = args.includes('--force') || args.includes('-f');
  const targetDir = process.cwd();

  console.log('[lumenflow init] Scaffolding LumenFlow project...');

  const result = await scaffoldProject(targetDir, { force });

  if (result.created.length > 0) {
    console.log('\nCreated:');
    result.created.forEach((f) => console.log(`  ✅ ${f}`));
  }

  if (result.skipped.length > 0) {
    console.log('\nSkipped (already exists, use --force to overwrite):');
    result.skipped.forEach((f) => console.log(`  ⏭️  ${f}`));
  }

  console.log('\n[lumenflow init] Done! Next steps:');
  console.log('  1. Edit .lumenflow.yaml to match your project structure');
  console.log('  2. Review CLAUDE.md and AGENTS.md templates');
  console.log('  3. Run: pnpm wu:create --id WU-0001 --lane <lane> --title "First WU"');
}
