// Copyright (c) 2026 Hellmai Ltd
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * @file Tests for wu-done staging whitelist patterns
 * @see WU-1072: Fix staging whitelist for auto-generated docs
 */

import { describe, it, expect } from 'vitest';

/**
 * Pattern matching logic extracted from validateStagedFiles in wu-done.ts
 * This tests the MDX whitelist pattern added in WU-1072
 */
function isWhitelistedAutoGeneratedDoc(file: string): boolean {
  return file.startsWith('apps/docs/') && file.endsWith('.mdx');
}

function isWhitelistedMetadataPath(
  file: string,
  baseWhitelist: string[],
  metadataAllowlist: string[] = [],
): boolean {
  const whitelist = new Set([...baseWhitelist, ...metadataAllowlist]);
  if (whitelist.has(file)) return true;
  if (file.startsWith('.lumenflow/stamps/')) return true;
  return false;
}

describe('wu-done staging whitelist', () => {
  describe('auto-generated docs pattern (WU-1072)', () => {
    it('should whitelist MDX files in apps/docs/', () => {
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/api/wu-create.mdx')).toBe(true);
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/commands/gates.mdx')).toBe(true);
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/nested/deep/file.mdx')).toBe(true);
    });

    it('should not whitelist MDX files outside apps/docs/', () => {
      expect(isWhitelistedAutoGeneratedDoc('docs/something.mdx')).toBe(false);
      expect(isWhitelistedAutoGeneratedDoc('packages/cli/README.mdx')).toBe(false);
      expect(isWhitelistedAutoGeneratedDoc('src/docs/file.mdx')).toBe(false);
    });

    it('should not whitelist non-MDX files in apps/docs/', () => {
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/config.ts')).toBe(false);
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/package.json')).toBe(false);
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/styles.css')).toBe(false);
    });

    it('should not whitelist files with mdx in the path but not as extension', () => {
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/mdx-utils/helper.ts')).toBe(false);
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/mdx')).toBe(false);
    });
  });

  describe('initiative metadata allowlist (WU-1572)', () => {
    const baseWhitelist = [
      'docs/04-operations/tasks/wu/WU-1572.yaml',
      'docs/04-operations/tasks/status.md',
      'docs/04-operations/tasks/backlog.md',
      '.lumenflow/state/wu-events.jsonl',
    ];

    it('should allow the current parent initiative YAML when explicitly allowlisted', () => {
      const currentParentInit = 'docs/04-operations/tasks/initiatives/INIT-021.yaml';

      expect(isWhitelistedMetadataPath(currentParentInit, baseWhitelist, [currentParentInit])).toBe(
        true,
      );
    });

    it('should reject other initiative YAML files not in the allowlist', () => {
      const currentParentInit = 'docs/04-operations/tasks/initiatives/INIT-021.yaml';
      const otherInit = 'docs/04-operations/tasks/initiatives/INIT-999.yaml';

      expect(isWhitelistedMetadataPath(otherInit, baseWhitelist, [currentParentInit])).toBe(false);
    });
  });
});
