/**
 * @file Tests for wu-done staging whitelist patterns
 * @see WU-1072: Fix staging whitelist for auto-generated docs
 */

import { describe, it, expect } from 'vitest';

/**
 * Pattern matching logic extracted from validateStagedFiles in wu-done.ts
 * This tests the MDX whitelist pattern added in WU-1072
 */
function isWhitelistedAutoGeneratedDoc(file: string): boolean {
  return file.startsWith('apps/docs/') && file.endsWith('.mdx');
}

describe('wu-done staging whitelist', () => {
  describe('auto-generated docs pattern (WU-1072)', () => {
    it('should whitelist MDX files in apps/docs/', () => {
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/api/wu-create.mdx')).toBe(true);
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/commands/gates.mdx')).toBe(true);
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/nested/deep/file.mdx')).toBe(true);
    });

    it('should not whitelist MDX files outside apps/docs/', () => {
      expect(isWhitelistedAutoGeneratedDoc('docs/something.mdx')).toBe(false);
      expect(isWhitelistedAutoGeneratedDoc('packages/cli/README.mdx')).toBe(false);
      expect(isWhitelistedAutoGeneratedDoc('src/docs/file.mdx')).toBe(false);
    });

    it('should not whitelist non-MDX files in apps/docs/', () => {
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/config.ts')).toBe(false);
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/package.json')).toBe(false);
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/styles.css')).toBe(false);
    });

    it('should not whitelist files with mdx in the path but not as extension', () => {
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/mdx-utils/helper.ts')).toBe(false);
      expect(isWhitelistedAutoGeneratedDoc('apps/docs/mdx')).toBe(false);
    });
  });
});
